# Generated by Django 4.1.4 on 2023-04-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('isMissed', models.BooleanField(default=False)),
                ('auto_complete', models.BooleanField(default=False)),
                ('added_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('totalTime', models.IntegerField(default=0)),
            ],
        ),
    ]
