# Generated by Django 4.1.4 on 2023-03-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isMissed',
            field=models.BooleanField(default=False),
        ),
    ]
