# Generated by Django 4.1.4 on 2023-04-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_end_time_alter_todo_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='totalTime',
            field=models.IntegerField(default=0),
        ),
    ]
