# Generated by Django 4.1.4 on 2023-03-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='activity_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
